add getTokenERC721s to SDK
KyuzanInc/mint-sdk-js pull request #188
Opened 2022-06-16 18:06 UTC by NSns24

task: https://app.clickup.com/t/2nab0mu
## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

no getTokenERC721s implementation

## What is the new behavior?
add getTokenERC721s implementation

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2022-06-16 18:09 UTC, NSns24 commented
Example usage:

https://user-images.githubusercontent.com/33995454/174137358-f97b030e-a934-4b39-82c9-0d2ccf5b3177.mov

2022-06-17 05:53 UTC, tomonari-t requested changes
I said it in MTG, but I have wrote it here for the log.

Plz, add a new example to https://github.com/KyuzanInc/mint-sdk-examples for testing and new clients

2022-06-17 05:53 UTC, tomonari-t commented on src/index.ts
> +   * Returns TokenERC721 list from the specified contractAddress.
nice comment!

2022-07-02 14:33 UTC, NSns24 commented
> I said it in MTG, but I have wrote it here for the log.
> 
> Plz, add a new example to https://github.com/KyuzanInc/mint-sdk-examples for testing and new clients

Added the new example https://github.com/KyuzanInc/mint-sdk-examples/pull/47, thank you

2022-07-04 20:59 UTC, tomonari-t approved these changes

2022-07-05 14:32 UTC, merged