[WIP] アイテム引き出し成功画面の表示
KyuzanInc/mint-sdk-js pull request #45
Opened 2021-06-02 13:47 UTC by ReonaN

## チケットへのリンク

- https://app.clickup.com/t/8g2b0m

## やったこと

- アイテム引き出し成功時に表示するページの作成

## やらないこと

- なし

## できるようになること（ユーザ目線）

- 成功画面が見える。
- ツイッターにシェアできる

## できなくなること（ユーザ目線）

- なし

## 動作確認

- どのような動作確認を行ったのか？　結果はどうか？
- UI が関わるものは、スクショや動画を添付

## その他

- レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

2021-06-22 06:28 UTC, tomonari-t commented on example/package.json
> +    "framer-motion": "^4.1.17",
`framer-motion`はしんたろーさんに導入前に調査をしてもらうことにしました。
今回は導入せずでおけですmm

2021-07-30 10:59 UTC, ReonaN commented on example/package.json
> +    "framer-motion": "^4.1.17",
了解しました！今回モーダルだすだけにします！

2021-08-18 10:51 UTC, tomonari-t commented on example/src/components/molecules/WithdrawModal/index.tsx
> +import styled from '@emotion/styled'
ここ、他で使う想定なさそうですね。
あえてコンポーネント分けた意図何かありますか？

2021-08-18 10:55 UTC, tomonari-t commented on example/src/components/organisms/WithdrawSuccess/presentation.tsx
> +  min-width: 840px;
Broad Peak、SPもデフォで対応することになりましたmm
共有できていなくすいません。カラムを落とすなど、っぽいレイアウトになるようにお願いします。

2021-08-18 10:57 UTC, tomonari-t commented on example/src/components/molecules/WithdrawModal/index.tsx
> +import styled from '@emotion/styled'
意図として、Organismsのプレゼンテーションにまとめても同じかなと。

2021-08-24 14:17 UTC, ReonaN commented on example/src/components/molecules/WithdrawModal/index.tsx
> +import styled from '@emotion/styled'
bidModalが入っていたのでModalはmolecules に入れたほうがいいかなと思っていました。確かにPresentationに含めてしまってもいいかもです！

2021-08-29 09:06 UTC, ReonaN commented on example/src/components/atoms/MediaContent/index.tsx
> +  @media (max-width: 440px) {
utilありがとうございます！！修正しました！

2021-08-29 09:08 UTC, ReonaN commented on example/src/pages/items/[itemId]/withdraw/index.tsx
> +import React from 'react'
固定価格も購入後に成功画面に遷移するようにしました。
UIの文言は購入完了しました！なのでそのままにしてます。
Page名はsuccessに変更しました

2021-08-29 09:08 UTC, ReonaN commented on example/src/pages/_document.tsx
> +          <meta name="viewport" content="width=device-width,initial-scale=1" />
知りませんでした！便利ですね…！上の一行はけしましたー

2021-08-29 09:09 UTC, ReonaN commented on example/src/components/molecules/WithdrawModal/index.tsx
> +import styled from '@emotion/styled'
ページのほうに集約させましたｍｍ

2021-08-30 09:59 UTC, tomonari-t requested changes
あざます！
いくつかコメントしましたmm

2021-08-30 09:59 UTC, tomonari-t commented on example/src/components/organisms/WithdrawSuccess/index.stories.tsx
> +  // signatureBuyAuction: undefined,
不要であれば削除をお願いします

2021-08-30 09:59 UTC, tomonari-t commented on example/src/components/organisms/WithdrawSuccess/modal.tsx
> +    display: flex;
`display: flex;`
上で書いたものは引き継がれるので、再度ここで定義しなくても大丈夫です。

2021-08-31 14:41 UTC, ReonaN commented
コメント部分修正しましたmm

2021-09-01 00:54 UTC, tomonari-t approved these changes
LGTM!

2021-09-06 07:18 UTC, merged