AuctionがEndした際に、Endの表示になる
KyuzanInc/mint-sdk-js pull request #54
Opened 2021-06-20 03:19 UTC by ReonaN

## チケットへのリンク

- https://app.clickup.com/t/8m1yej

## やったこと

- MyPage上でオークションが終了したときに、データを再読み込みし、End表示させるようにしました

## やらないこと

- なし

## できるようになること（ユーザ目線）

- なし

## できなくなること（ユーザ目線）

- なし

## 動作確認

- 残り10秒くらいにしてカードを表示すると0になったときにデータ再読み込みしているところまで確認済

## その他

- レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

2021-06-21 06:54 UTC, tomonari-t requested changes
コメントしました！

2021-06-21 06:54 UTC, tomonari-t commented on example/src/components/molecules/CardMyPage/index.tsx
> +  onComplete?: () => void
オークションが終わりなので、`onFinish`, `onEnd`, `onAuctionEnd`とかが良さそうかなと思いました。

2021-06-21 06:54 UTC, tomonari-t commented on example/src/components/molecules/CardMyPage/index.tsx
> +              onComplete={onComplete}
シンプルなIFで使いやすそうです:+1:

2021-06-23 13:40 UTC, ReonaN commented on example/src/components/molecules/CardMyPage/index.tsx
> +  onComplete?: () => void
使っているライブラリ(`react-countdown`)が指定しているfuncの名前が`onComplete`なのでそうしております！

2021-06-23 13:48 UTC, tomonari-t commented on example/src/components/molecules/CardMyPage/index.tsx
> +  onComplete?: () => void
なるほど。了解です！

2021-06-23 13:48 UTC, tomonari-t approved these changes
LGTM

2021-06-23 15:10 UTC, merged