[WIP]Bidに成功したら成功ページを表示する
KyuzanInc/mint-sdk-js pull request #62
Opened 2021-06-29 15:26 UTC by ReonaN

## チケットへのリンク

- https://app.clickup.com/t/89yyv8

## やったこと

- Bidに成功したら成功モーダルを表示

## やらないこと

- なし

## できるようになること（ユーザ目線）

- 成功モーダルが見える

## できなくなること（ユーザ目線）

- なし

## 動作確認

- どのような動作確認を行ったのか？　結果はどうか？
- UI が関わるものは、スクショや動画を添付

## その他

- レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

2021-07-12 05:08 UTC, tomonari-t requested changes
コメントしましたmm

2021-07-12 05:08 UTC, tomonari-t commented on example/src/redux/transaction/index.ts
> +    status: string
`status`は決まった文字列が入りそうですね。
`type`として定義しましょう。

2021-07-12 05:08 UTC, tomonari-t commented on example/src/components/atoms/SimpleButton/index.stories.tsx
> +import { action } from '@storybook/addon-actions'
StoryBookあざす！

2021-07-12 12:26 UTC, ReonaN commented on example/src/redux/transaction/index.ts
> +    status: string
'Status' type を追加しました！

2021-07-13 03:00 UTC, tomonari-t commented on example/src/redux/transaction/index.ts
> +    status: string
こちら反映されていない？ようです

2021-07-13 04:49 UTC, tomonari-t approved these changes
LGTM!

2021-07-14 11:21 UTC, merged