フッターの作成
KyuzanInc/mint-sdk-js pull request #63
Opened 2021-07-08 15:01 UTC by ReonaN

## チケットへのリンク

- https://app.clickup.com/t/8m21g2
-
## やったこと

-　フッターのUIの作成

## やらないこと

- フッターの各リンク先はまだ入れていません

## できるようになること（ユーザ目線）

- フッターが見える
## できなくなること（ユーザ目線）

- なし

## 動作確認

![Screenshot 2021-07-09 000103](https://user-images.githubusercontent.com/8515141/124945067-cc03cb80-e048-11eb-88aa-9adea275af65.png)

## その他

- レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

2021-07-12 04:37 UTC, tomonari-t commented on example/src/components/organisms/Footer/presentation.tsx
> +export const Presentation: React.VFC = () => {
仕様追加をしたいですmm

フッターのリンクをそれぞれprops経由で渡せるようにして、指定なければ表示させないという形にしてもらって良いでしょうか？併せてロゴの画像 もPropsで渡せるようにしたいです。

そして、現時点ではロゴ画像のURL以外は空（非表示）でお願いしますmm

2021-07-12 04:37 UTC, tomonari-t requested changes
ありがとうございます！
仕様変更一点コメントしました。

2021-07-12 12:50 UTC, ReonaN commented on example/src/components/organisms/Footer/presentation.tsx
> +export const Presentation: React.VFC = () => {
props経由で渡せるようにしました！storybookにも追加済みです！現時点ではロゴ以外表示されないようになっています。

2021-07-13 02:58 UTC, tomonari-t approved these changes
ありがとうございます！LGTM!

2021-07-14 11:21 UTC, merged