fix primary button type in example
KyuzanInc/mint-sdk-js pull request #80
Opened 2021-11-06 13:18 UTC by maruhiko

## チケットへのリンク
#77 

## やったこと

- このプルリクで何をしたのか？
- Primary button の typeがsubmitで固定だったのをpropsから指定できるようにした

## やらないこと

- このプルリクでやらないことは何か？（あれば。無いなら「無し」で OK）（やらない場合は、いつやるのかを明記する。）
- なし

## できるようになること（ユーザ目線）

- 何ができるようになるのか？（あれば。無いなら「無し」で OK）
- なし

## できなくなること（ユーザ目線）

- 何ができなくなるのか？（あれば。無いなら「無し」で OK）
- なし

## 動作確認

- どのような動作確認を行ったのか？　結果はどうか？
- UI が関わるものは、スクショや動画を添付

## その他

- レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

2021-11-15 11:17 UTC, tomonari-t requested changes
あざす！コメントしましたmm

2021-11-15 11:17 UTC, tomonari-t commented on example/src/components/atoms/PrimaryButton/index.tsx
> +  type?: 'submit' | 'button' | 'reset' | undefined
型は既存の方があり使える場合は使った方がお得ですね。
今回だと以下。
```diff
- type?: 'submit' | 'button' | 'reset' | undefined
+ type?: ButtonHTMLAttributes<HTMLButtonElement>['type']
```

2021-11-17 12:16 UTC, maruhiko commented
@tomonari-t 該当箇所の修正完了しました

2021-11-25 00:45 UTC, merged

2021-11-25 00:46 UTC, tomonari-t commented
close #80

2021-11-25 00:47 UTC, tomonari-t commented
close #77